version: "3"
services:
  node-app:
    build: .
    container_name: dockweiler-watch-server
    ports:
      - "80:80"
    depends_on:
      - "db"
    restart: always
  db:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db
    restart: always

volumes:
  mongo-db:
