version: "3"
services:
  node-app:
    build: .
    container_name: dockweiler-watch-server
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
